/// <filename>
///     MarketRegistered.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Events
{
  public class MarketRegistered : ZES.Infrastructure.Domain.Event
  {
    public MarketRegistered() 
    {
    }  
    public string FamilyName
    {
       get; 
       set;
    }  
    public MarketRegistered(string familyName) 
    {
      FamilyName = familyName;
    }
  }
}

