/// <filename>
///     MarketItemAdded.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Events
{
  public class MarketItemAdded : ZES.Infrastructure.Domain.Event
  {
    public MarketItemAdded() 
    {
    }  
    public string Item
    {
       get; 
       set;
    }  
    public string FamilyName
    {
       get; 
       set;
    }  
    public MarketItemAdded(string item, string familyName) 
    {
      Item = item; 
      FamilyName = familyName;
    }
  }
}

