/// <filename>
///     MarketItemInfoUpdated.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Events
{
  public class MarketItemInfoUpdated : ZES.Infrastructure.Domain.Event
  {
    public MarketItemInfoUpdated() 
    {
    }  
    public int[] Amounts
    {
       get; 
       set;
    }  
    public double[] Prices
    {
       get; 
       set;
    }  
    public MarketItemInfoUpdated(int[] amounts, double[] prices) 
    {
      Amounts = amounts; 
      Prices = prices;
    }
  }
}

