/// <filename>
///     ItemInfoQuery.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Core.Queries
{
  public class ItemInfoQuery : ZES.Infrastructure.Domain.SingleQuery<ItemInfo>
  {
    public string Name
    {
       get; 
       set;
    }  
    public int Grade
    {
       get; 
       set;
    }  
    public ItemInfoQuery() 
    {
    }  
    public ItemInfoQuery(string name, int grade) : base($"{name}_{grade}") 
    {
      Name = name; 
      Grade = grade;
    }
  }
}

