/// <filename>
///     ItemInfoQueryHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Core.Queries
{
  public class ItemInfoQueryHandler : ZES.Interfaces.Domain.IProjectionHandler<ItemInfo,BDO.Core.Events.ItemAdded>, ZES.Interfaces.Domain.IProjectionHandler<ItemInfo,BDO.Core.Events.ItemInfoUpdated>
  {
    public ItemInfo Handle (ZES.Interfaces.IEvent e, ItemInfo state)
    {
      Handle((dynamic) e, state); 
      return state;
    }  
    public ItemInfo Handle (BDO.Core.Events.ItemAdded e, ItemInfo state)
    {
      state.Name = e.Name; 
      return state;
    }  
    public ItemInfo Handle (BDO.Core.Events.ItemInfoUpdated e, ItemInfo state)
    {
      state.ItemId = e.ItemId; 
      state.Grade = e.Grade; 
      return state;
    }
  }
}

