/// <filename>
///     EnhancementTest.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement
{
  public class EnhancementTest : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public EnhancementTest() 
    {
      Register<BDO.Enhancement.Events.EnhancementTestCreated>(ApplyEvent); 
      Register<BDO.Enhancement.Events.EnhancementTestCompleted>(ApplyEvent);
    }  
    public EnhancementTest(string enhancementId, int numberOfPaths, string itemId, int grade, int initialFailstack) : this() 
    {
      When(new BDO.Enhancement.Events.EnhancementTestCreated(enhancementId, numberOfPaths, itemId, grade, initialFailstack));
    }  
    public string EnhancementId
    {
       get; 
       set;
    }  
    public int NumberOfPaths
    {
       get; 
       set;
    }  
    public string ItemId
    {
       get; 
       set;
    }  
    public int Grade
    {
       get; 
       set;
    }  
    public int InitialFailstack
    {
       get; 
       set;
    }  
    public int NumberOfFailures
    {
       get; 
       set;
    }  
    public void Complete (int numberOfFailures)
    {
      When(new BDO.Enhancement.Events.EnhancementTestCompleted(Id, numberOfFailures));
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementTestCreated e)
    {
      Id = e.EnhancementId; 
      NumberOfPaths = e.NumberOfPaths; 
      ItemId = e.ItemId; 
      Grade = e.Grade; 
      InitialFailstack = e.InitialFailstack;
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementTestCompleted e)
    {
      NumberOfFailures = e.NumberOfFailures;
    }
  }
}

