/// <filename>
///     Enhancement.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement
{
  public class Enhancement : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public Enhancement() 
    {
      Register<BDO.Enhancement.Events.EnhancementStarted>(ApplyEvent); 
      Register<BDO.Enhancement.Events.EnhancementSucceeded>(ApplyEvent); 
      Register<BDO.Enhancement.Events.EnhancementFailed>(ApplyEvent);
    }  
    public Enhancement(string enchancementId, string item, int grade, int failstack) : this() 
    {
      When(new BDO.Enhancement.Events.EnhancementStarted(enchancementId, item, grade, failstack));
    }  
    public string EnchancementId
    {
       get; 
       set;
    }  
    public string Item
    {
       get; 
       set;
    }  
    public int Grade
    {
       get; 
       set;
    }  
    public int Failstack
    {
       get; 
       set;
    }  
    public int NumberOfFailures
    {
       get; 
       set;
    }  
    public void Success (int numberOfFailures)
    {
      When(new BDO.Enhancement.Events.EnhancementSucceeded(Id, numberOfFailures));
    }  
    public void Failure ()
    {
      When(new BDO.Enhancement.Events.EnhancementFailed(Id));
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementStarted e)
    {
      Id = e.EnchancementId; 
      Item = e.Item; 
      Grade = e.Grade; 
      Failstack = e.Failstack;
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementSucceeded e)
    {
      NumberOfFailures = e.NumberOfFailures;
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementFailed e)
    {
    }
  }
}

