/// <filename>
///     Enhancement.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement
{
  public class Enhancement : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public Enhancement() 
    {
      Register<BDO.Enhancement.Events.EnhancementStarted>(ApplyEvent); 
      Register<BDO.Enhancement.Events.EnhancementSucceeded>(ApplyEvent); 
      Register<BDO.Enhancement.Events.EnhancementFailed>(ApplyEvent); 
      Register<BDO.Enhancement.Events.EnhancementInfoSet>(ApplyEvent);
    }  
    public Enhancement(string enchancementId) : this() 
    {
      When(new BDO.Enhancement.Events.EnhancementStarted(enchancementId));
    }  
    public string EnchancementId
    {
       get; 
       set;
    }  
    public string ItemId
    {
       get; 
       set;
    }  
    public string EnhancementItemId
    {
       get; 
       set;
    }  
    public int EnhancementItemAmount
    {
       get; 
       set;
    }  
    public int InitialFilestack
    {
       get; 
       set;
    }  
    public double BaseChance
    {
       get; 
       set;
    }  
    public double BaseIncrease
    {
       get; 
       set;
    }  
    public double SoftCap
    {
       get; 
       set;
    }  
    public double SoftCapIncrease
    {
       get; 
       set;
    }  
    public void Success ()
    {
      When(new BDO.Enhancement.Events.EnhancementSucceeded(Id));
    }  
    public void Failure ()
    {
      When(new BDO.Enhancement.Events.EnhancementFailed(Id));
    }  
    public void SetInfo (string enchancementId, string itemId, string enhancementItemId, int enhancementItemAmount, int initialFilestack, double baseChance, double baseIncrease, double softCap, double softCapIncrease)
    {
      When(new BDO.Enhancement.Events.EnhancementInfoSet(enchancementId, itemId, enhancementItemId, enhancementItemAmount, initialFilestack, baseChance, baseIncrease, softCap, softCapIncrease));
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementStarted e)
    {
      Id = e.EnchancementId;
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementSucceeded e)
    {
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementFailed e)
    {
    }  
    private void ApplyEvent (BDO.Enhancement.Events.EnhancementInfoSet e)
    {
      EnchancementId = e.EnchancementId; 
      ItemId = e.ItemId; 
      EnhancementItemId = e.EnhancementItemId; 
      EnhancementItemAmount = e.EnhancementItemAmount; 
      InitialFilestack = e.InitialFilestack; 
      BaseChance = e.BaseChance; 
      BaseIncrease = e.BaseIncrease; 
      SoftCap = e.SoftCap; 
      SoftCapIncrease = e.SoftCapIncrease;
    }
  }
}

