/// <filename>
///     AddItem.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Core.Commands
{
  public class AddItem : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public AddItem() 
    {
    }  
    public AddItem(string target) : base(target) 
    {
    }
  }
}

