/// <filename>
///     UpdateItemInfo.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Core.Commands
{
  public class UpdateItemInfo : ZES.Infrastructure.Domain.Command
  {
    public UpdateItemInfo() 
    {
    }  
    public int ItemId
    {
       get; 
       set;
    }  
    public UpdateItemInfo(string name, int grade, int itemId) : base($"{name}_{grade}") 
    {
      ItemId = itemId;
    }
  }
}

