/// <filename>
///     UpdateItemInfoHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Core.Commands
{
  public class UpdateItemInfoHandler : ZES.Infrastructure.Domain.CommandHandlerBase<UpdateItemInfo, Item>
  {
    public UpdateItemInfoHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Item item, UpdateItemInfo command)
    {
      item.UpdateInfo(command.ItemId);
    }
  }
}

