/// <filename>
///     UpdateItemInfo.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Core.Commands
{
  public class UpdateItemInfo : ZES.Infrastructure.Domain.Command
  {
    public UpdateItemInfo() 
    {
    }  
    public int ItemId
    {
       get;
    }  
    public int Grade
    {
       get;
    }  
    public UpdateItemInfo(string target, int itemId, int grade) : base(target) 
    {
      ItemId = itemId; 
      Grade = grade;
    }
  }
}

