/// <filename>
///     EnhancementResultsQuery.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Queries
{
  public class EnhancementResultsQuery : ZES.Infrastructure.Domain.SingleQuery<EnhancementResults>
  {
    public string ItemId
    {
       get;
    }  
    public EnhancementResultsQuery() 
    {
    }  
    public EnhancementResultsQuery(string itemId) : base(itemId) 
    {
      ItemId = itemId;
    }
  }
}

