/// <filename>
///     EnhancementResults.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Queries
{
  public class EnhancementResults : ZES.Interfaces.Domain.ISingleState
  {
    public EnhancementResults()
    {
    }  
    public int NumberOfAttempts
    {
       get; 
       set;
    }  
    public EnhancementResults(int numberOfAttempts) 
    {
      NumberOfAttempts = numberOfAttempts;
    }
  }
}

