/// <filename>
///     EnhancementTestResult.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Queries
{
  public class EnhancementTestResult : ZES.Interfaces.Domain.IState
  {
    public EnhancementTestResult() 
    {
    }  
    public int NumberOfFailures
    {
       get; 
       set;
    }  
    public EnhancementTestResult(int numberOfFailures) 
    {
      NumberOfFailures = numberOfFailures;
    }
  }
}

