/// <filename>
///     EnhancementResultsQueryHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Queries
{
  public class EnhancementResultsQueryHandler : ZES.Interfaces.Domain.IProjectionHandler<EnhancementResults,BDO.Enhancement.Events.EnhancementFailed>
  {
    public EnhancementResults Handle (ZES.Interfaces.IEvent e, EnhancementResults state)
    {
      Handle((dynamic) e, state); 
      return state;
    }  
    public EnhancementResults Handle (BDO.Enhancement.Events.EnhancementFailed e, EnhancementResults state)
    {
      state.NumberOfAttempts++;
      return state;
    }
  }
}

