/// <filename>
///     Market.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market
{
  public class Market : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public Market() 
    {
      Register<BDO.Market.Events.MarketRegistered>(ApplyEvent); 
      Register<BDO.Market.Events.CookieSet>(ApplyEvent);
    }  
    public Market(string familyName) : this() 
    {
      When(new BDO.Market.Events.MarketRegistered(familyName));
    }  
    public string Cookie
    {
       get; 
       set;
    }  
    public void SetCookie (string cookie)
    {
      When(new BDO.Market.Events.CookieSet(cookie));
    }  
    private void ApplyEvent (BDO.Market.Events.MarketRegistered e)
    {
      Id = e.FamilyName;
    }  
    private void ApplyEvent (BDO.Market.Events.CookieSet e)
    {
      Cookie = e.Cookie;
    }
  }
}

