/// <filename>
///     MarketItem.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market
{
  public class MarketItem : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public MarketItem() 
    {
      Register<BDO.Market.Events.MarketItemAdded>(ApplyEvent); 
      Register<BDO.Market.Events.MarketItemInfoUpdated>(ApplyEvent);
    }  
    public MarketItem(string item, string familyName) : this() 
    {
      When(new BDO.Market.Events.MarketItemAdded(item, familyName));
    }  
    public string Item
    {
       get; 
       set;
    }  
    public string FamilyName
    {
       get; 
       set;
    }  
    public int[] Amounts
    {
       get; 
       set;
    }  
    public double[] Prices
    {
       get; 
       set;
    }  
    public void UpdateInfo (int[] amounts, double[] prices)
    {
      When(new BDO.Market.Events.MarketItemInfoUpdated(amounts, prices));
    }  
    private void ApplyEvent (BDO.Market.Events.MarketItemAdded e)
    {
      Id = e.Item; 
      FamilyName = e.FamilyName;
    }  
    private void ApplyEvent (BDO.Market.Events.MarketItemInfoUpdated e)
    {
      Amounts = e.Amounts; 
      Prices = e.Prices;
    }
  }
}

