/// <filename>
///     ItemInfoUpdated.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Core.Events
{
  public class ItemInfoUpdated : ZES.Infrastructure.Domain.Event
  {
    public ItemInfoUpdated() 
    {
    }  
    public int ItemId
    {
       get; 
       set;
    }  
    public int Grade
    {
       get; 
       set;
    }  
    public ItemInfoUpdated(int itemId, int grade) 
    {
      ItemId = itemId; 
      Grade = grade;
    }
  }
}

