/// <filename>
///     EnhancementTestCompleted.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Events
{
  public class EnhancementTestCompleted : ZES.Infrastructure.Domain.Event
  {
    public EnhancementTestCompleted() 
    {
    }  
    public string Id
    {
       get; 
       set;
    }  
    public int NumberOfFailures
    {
       get; 
       set;
    }  
    public EnhancementTestCompleted(string id, int numberOfFailures) 
    {
      Id = id; 
      NumberOfFailures = numberOfFailures;
    }
  }
}

