/// <filename>
///     EnhancementStarted.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Events
{
  public class EnhancementStarted : ZES.Infrastructure.Domain.Event
  {
    public EnhancementStarted() 
    {
    }  
    public string EnchancementId
    {
       get; 
       set;
    }  
    public string Item
    {
       get; 
       set;
    }  
    public int Grade
    {
       get; 
       set;
    }  
    public int Failstack
    {
       get; 
       set;
    }  
    public EnhancementStarted(string enchancementId, string item, int grade, int failstack) 
    {
      EnchancementId = enchancementId; 
      Item = item; 
      Grade = grade; 
      Failstack = failstack;
    }
  }
}

