/// <filename>
///     EnhancementSucceeded.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Events
{
  public class EnhancementSucceeded : ZES.Infrastructure.Domain.Event
  {
    public EnhancementSucceeded() 
    {
    }  
    public string Id
    {
       get; 
       set;
    }  
    public EnhancementSucceeded(string id) 
    {
      Id = id;
    }
  }
}

