/// <filename>
///     EnhancementTestCreated.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Events
{
  public class EnhancementTestCreated : ZES.Infrastructure.Domain.Event
  {
    public EnhancementTestCreated() 
    {
    }  
    public string EnhancementId
    {
       get; 
       set;
    }  
    public int NumberOfPaths
    {
       get; 
       set;
    }  
    public string ItemId
    {
       get; 
       set;
    }  
    public int Grade
    {
       get; 
       set;
    }  
    public int InitialFailstack
    {
       get; 
       set;
    }  
    public EnhancementTestCreated(string enhancementId, int numberOfPaths, string itemId, int grade, int initialFailstack) 
    {
      EnhancementId = enhancementId; 
      NumberOfPaths = numberOfPaths; 
      ItemId = itemId; 
      Grade = grade; 
      InitialFailstack = initialFailstack;
    }
  }
}

