/// <filename>
///     EnhancementStarted.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Events
{
  public class EnhancementStarted : ZES.Infrastructure.Domain.Event
  {
    public EnhancementStarted() 
    {
    }  
    public string EnchancementId
    {
       get; 
       set;
    }  
    public EnhancementStarted(string enchancementId) 
    {
      EnchancementId = enchancementId;
    }
  }
}

