/// <filename>
///     AddMarketItemHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Commands
{
  public class AddMarketItemHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<AddMarketItem, MarketItem>
  {
    public AddMarketItemHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override MarketItem Create (AddMarketItem command)
    {
      return new MarketItem(command.Target, command.FamilyName);
    }
  }
}

