/// <filename>
///     RegisterMarketHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Commands
{
  public class RegisterMarketHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<RegisterMarket, Market>
  {
    public RegisterMarketHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Market Create (RegisterMarket command)
    {
      return new Market(command.Target);
    }
  }
}

