/// <filename>
///     RegisterMarket.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Commands
{
  public class RegisterMarket : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public RegisterMarket() 
    {
    }  
    public RegisterMarket(string target) : base(target) 
    {
    }
  }
}

