/// <filename>
///     SetCookieHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Commands
{
  public class SetCookieHandler : ZES.Infrastructure.Domain.CommandHandlerBase<SetCookie, Market>
  {
    public SetCookieHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Market market, SetCookie command)
    {
      market.SetCookie(command.Cookie);
    }
  }
}

