/// <filename>
///     SetCookie.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Commands
{
  public class SetCookie : ZES.Infrastructure.Domain.Command
  {
    public SetCookie() 
    {
    }  
    public string Cookie
    {
       get;
    }  
    public SetCookie(string target, string cookie) : base(target) 
    {
      Cookie = cookie;
    }
  }
}

