/// <filename>
///     UpdateMarketItemInfoHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Market.Commands
{
  public class UpdateMarketItemInfoHandler : ZES.Infrastructure.Domain.CommandHandlerBase<UpdateMarketItemInfo, MarketItem>
  {
    public UpdateMarketItemInfoHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (MarketItem marketItem, UpdateMarketItemInfo command)
    {
      marketItem.UpdateInfo(command.Amounts, command.Prices);
    }
  }
}

