/// <filename>
///     Item.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Core
{
  public class Item : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public Item() 
    {
      Register<BDO.Core.Events.ItemAdded>(ApplyEvent); 
      Register<BDO.Core.Events.ItemInfoUpdated>(ApplyEvent);
    }  
    public Item(string name) : this() 
    {
      When(new BDO.Core.Events.ItemAdded(name));
    }  
    public int ItemId
    {
       get; 
       set;
    }  
    public int Grade
    {
       get; 
       set;
    }  
    public void UpdateInfo (int itemId, int grade)
    {
      When(new BDO.Core.Events.ItemInfoUpdated(itemId, grade));
    }  
    private void ApplyEvent (BDO.Core.Events.ItemAdded e)
    {
      Id = e.Name;
    }  
    private void ApplyEvent (BDO.Core.Events.ItemInfoUpdated e)
    {
      ItemId = e.ItemId; 
      Grade = e.Grade;
    }
  }
}

