/// <filename>
///     CreateEnhancementTestHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class CreateEnhancementTestHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateEnhancementTest, EnhancementTest>
  {
    public CreateEnhancementTestHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override EnhancementTest Create (CreateEnhancementTest command)
    {
      return new EnhancementTest(command.Target, command.NumberOfPaths, command.ItemId, command.Grade, command.InitialFailstack);
    }
  }
}

