/// <filename>
///     FailEnhancement.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class FailEnhancement : ZES.Infrastructure.Domain.Command
  {
    public FailEnhancement() 
    {
    }  
    public FailEnhancement(string target) : base(target) 
    {
    }
  }
}

