/// <filename>
///     FailEnhancementHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class FailEnhancementHandler : ZES.Infrastructure.Domain.CommandHandlerBase<FailEnhancement, Enhancement>
  {
    public FailEnhancementHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Enhancement enhancement, FailEnhancement command)
    {
      enhancement.Failure();
    }
  }
}

