/// <filename>
///     SetEnhancementInfo.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class SetEnhancementInfo : ZES.Infrastructure.Domain.Command
  {
    public SetEnhancementInfo() 
    {
    }  
    public string ItemId
    {
       get;
    }  
    public string EnhancementItemId
    {
       get;
    }  
    public int EnhancementItemAmount
    {
       get;
    }  
    public int InitialFailstack
    {
       get;
    }  
    public double BaseChance
    {
       get;
    }  
    public double BaseIncrease
    {
       get;
    }  
    public double SoftCap
    {
       get;
    }  
    public double SoftCapIncrease
    {
       get;
    }  
    public SetEnhancementInfo(string target, string itemId, string enhancementItemId, int enhancementItemAmount, int initialFailstack, double baseChance, double baseIncrease, double softCap, double softCapIncrease) : base(target) 
    {
      ItemId = itemId; 
      EnhancementItemId = enhancementItemId; 
      EnhancementItemAmount = enhancementItemAmount; 
      InitialFailstack = initialFailstack; 
      BaseChance = baseChance; 
      BaseIncrease = baseIncrease; 
      SoftCap = softCap; 
      SoftCapIncrease = softCapIncrease;
    }
  }
}

