/// <filename>
///     SetEnhancementInfoHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class SetEnhancementInfoHandler : ZES.Infrastructure.Domain.CommandHandlerBase<SetEnhancementInfo, Enhancement>
  {
    public SetEnhancementInfoHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Enhancement enhancement, SetEnhancementInfo command)
    {
      enhancement.SetInfo(command.Target, command.ItemId, command.EnhancementItemId, command.EnhancementItemAmount, command.InitialFailstack, command.BaseChance, command.BaseIncrease, command.SoftCap, command.SoftCapIncrease);
    }
  }
}

