/// <filename>
///     StartEnhancement.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class StartEnhancement : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public StartEnhancement() 
    {
    }  
    public string Item
    {
       get;
    }  
    public int Grade
    {
       get;
    }  
    public int Failstack
    {
       get;
    }  
    public StartEnhancement(string target, string item, int grade, int failstack) : base(target) 
    {
      Item = item; 
      Grade = grade; 
      Failstack = failstack;
    }
  }
}

