/// <filename>
///     StartEnhancementHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class StartEnhancementHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<StartEnhancement, Enhancement>
  {
    public StartEnhancementHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Enhancement Create (StartEnhancement command)
    {
      return new Enhancement(command.Target, command.Item, command.Grade, command.Failstack);
    }
  }
}

