/// <filename>
///     StartEnhancement.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class StartEnhancement : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public StartEnhancement() 
    {
    }  
    public StartEnhancement(string target) : base(target) 
    {
    }
  }
}

