/// <filename>
///     SucceedEnhancement.cs
/// </filename>

// <auto-generated/>
namespace BDO.Enhancement.Commands
{
  public class SucceedEnhancement : ZES.Infrastructure.Domain.Command
  {
    public SucceedEnhancement() 
    {
    }  
    public int NumberOfFailures
    {
       get;
    }  
    public SucceedEnhancement(string target, int numberOfFailures) : base(target) 
    {
      NumberOfFailures = numberOfFailures;
    }
  }
}

