/// <filename>
///     SucceedEnhancement.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class SucceedEnhancement : ZES.Infrastructure.Domain.Command
  {
    public SucceedEnhancement() 
    {
    }  
    public SucceedEnhancement(string target) : base(target) 
    {
    }
  }
}

