/// <filename>
///     SucceedEnhancementHandler.cs
/// </filename>

// <auto-generated/>
 namespace BDO.Enhancement.Commands
{
  public class SucceedEnhancementHandler : ZES.Infrastructure.Domain.CommandHandlerBase<SucceedEnhancement, Enhancement>
  {
    public SucceedEnhancementHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Enhancement enhancement, SucceedEnhancement command)
    {
      enhancement.Success();
    }
  }
}

